### ISSUE TITLE
java.lang.ClassNotFoundException: org.dozer.CustomConverter

### ISSUE THREAD

**Issue by zxcstc1256** [GeBeater/dozer-jdk8-support#9]
'org.dozer.CustomConverter' is deprecated since Dozer 6.3.0 Use 'com.github.dozermapper.core.CustomConverter' instead.
https://github.com/DozerMapper/dozer/pull/582

**Comment by edeandrea** [comment]
Is supporting Dozer >= 6.3.0 anywhere on the radar?

**Comment by zxcstc1256** [comment]
> Is supporting Dozer >= 6.3.0 anywhere on the radar?

I fixed this bug in my fork. https://github.com/zxcstc1256/dozer-jdk8-support

**Comment by edeandrea** [comment]
@zxcstc1256 why don't you issue a PR so that the changes get worked in?

**Comment by zxcstc1256** [comment]
> @zxcstc1256 why don't you issue a PR so that the changes get worked in?

I have a PR. but... By the way, dozer >= 6.3.0 support jdk8 by default.
https://github.com/GeBeater/dozer-jdk8-support/pull/10

**Comment by GeBeater** [comment]
@zxcstc1256 Thanks for the pull request. I merged the pull request and released version 1.0.5. However, it may take a while until it is available in Maven Central.
